### ISSUE TITLE
Consertar o modo escuro

### ISSUE THREAD

**Issue by Gabriel-S-O** [ifpr-paranavai/BioMais#15]
Alterar a paleta de cores do style "dark" de modo que todo o app fique visível e agradável para o usuário. (no primeiro BioMais o modo escuro é completamente INUTILIZÁVEL)

OBS: é de EXTREMA importância essa implementação, pois dependendo das configurações do aparelho do usuário, o aplicativo é forçado ao modo escuro por padrão.

**Comment by frankwco** [comment]
fiz uma formatação css para incluir as imagens em um box com fundo cinza claro
